// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StartRef.Api.Data;

#nullable disable

namespace StartRef.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("StartRef.Api.Data.Entities.ChangeLogEntry", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
            b.Property<DateTimeOffset>("ChangedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("ChangedBy").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("");
            b.Property<DateOnly>("CompetitionDate").HasColumnType("date");
            b.Property<string>("FieldName").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("");
            b.Property<string>("NewValue").HasColumnType("nvarchar(max)");
            b.Property<string>("OldValue").HasColumnType("nvarchar(max)");
            b.Property<int>("StartNumber").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("CompetitionDate", "StartNumber");
            b.HasIndex("ChangedAtUtc");
            b.ToTable("ChangeLogEntries");
        });

        modelBuilder.Entity("StartRef.Api.Data.Entities.Class", b =>
        {
            b.Property<int>("Id").HasColumnType("int").ValueGeneratedNever();
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasDefaultValue("");
            b.Property<int>("StartPlace").HasColumnType("int").HasDefaultValue(0);
            b.HasKey("Id");
            b.ToTable("Classes");
        });

        modelBuilder.Entity("StartRef.Api.Data.Entities.Club", b =>
        {
            b.Property<int>("Id").HasColumnType("int").ValueGeneratedNever();
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasDefaultValue("");
            b.HasKey("Id");
            b.ToTable("Clubs");
        });

        modelBuilder.Entity("StartRef.Api.Data.Entities.Competition", b =>
        {
            b.Property<DateOnly>("Date").HasColumnType("date");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("Name").HasColumnType("nvarchar(max)");
            b.HasKey("Date");
            b.ToTable("Competitions");
        });

        modelBuilder.Entity("StartRef.Api.Data.Entities.Runner", b =>
        {
            b.Property<DateOnly>("CompetitionDate").HasColumnType("date");
            b.Property<int>("StartNumber").HasColumnType("int");
            b.Property<int>("ClassId").HasColumnType("int").HasDefaultValue(0);
            b.Property<int>("ClubId").HasColumnType("int").HasDefaultValue(0);
            b.Property<DateTimeOffset>("LastModifiedUtc").HasColumnType("datetimeoffset");
            b.Property<string>("LastModifiedBy").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("");
            b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("");
            b.Property<string>("SiChipNo").HasColumnType("nvarchar(max)");
            b.Property<TimeOnly?>("StartTime").HasColumnType("time");
            b.Property<int>("StatusId").HasColumnType("int").HasDefaultValue(1);
            b.Property<string>("Surname").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("");
            b.HasKey("CompetitionDate", "StartNumber");
            b.HasIndex("CompetitionDate", "LastModifiedUtc");
            b.ToTable("Runners");
        });

        modelBuilder.Entity("StartRef.Api.Data.Entities.Status", b =>
        {
            b.Property<int>("Id").HasColumnType("int").ValueGeneratedNever();
            b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.ToTable("Statuses");
            b.HasData(
                new { Id = 1, Name = "Registered" },
                new { Id = 2, Name = "Started" },
                new { Id = 3, Name = "DNS" });
        });

        modelBuilder.Entity("StartRef.Api.Data.Entities.Runner", b =>
        {
            b.HasOne("StartRef.Api.Data.Entities.Competition", "Competition")
                .WithMany("Runners")
                .HasForeignKey("CompetitionDate")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("StartRef.Api.Data.Entities.Status", "Status")
                .WithMany()
                .HasForeignKey("StatusId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Competition");
            b.Navigation("Status");
        });

        modelBuilder.Entity("StartRef.Api.Data.Entities.Competition", b =>
        {
            b.Navigation("Runners");
        });
#pragma warning restore 612, 618
    }
}
